# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "GenerateModuleHeader.cmake requires INPUT and OUTPUT")
endif()

file(READ "${INPUT}" module HEX)
string(LENGTH "${module}" hex_length)
set(header "// Generated from guest_zlib.c and the pinned zlib sources.\n")
string(APPEND header "static const unsigned char zlib_wasm_module[] = {\n")
set(offset 0)
while(offset LESS hex_length)
    set(line "    ")
    set(column 0)
    while(column LESS 16 AND offset LESS hex_length)
        string(SUBSTRING "${module}" ${offset} 2 byte)
        string(APPEND line "0x${byte}, ")
        math(EXPR offset "${offset} + 2")
        math(EXPR column "${column} + 1")
    endwhile()
    string(APPEND header "${line}\n")
endwhile()
string(APPEND header "};\n")
string(APPEND header "#define zlib_wasm_module_len ((unsigned)sizeof(zlib_wasm_module))\n")
file(WRITE "${OUTPUT}" "${header}")
