// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// Generate text with one llama2.c checkpoint in the kernel, the way run.c
// does it, then repeat the generation with the same upstream code compiled
// natively: the texts must match, and both execution times are reported.

#include <bpf/bpf.h>
#include <bpf/libbpf.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

#include "bpf_capsule_host.h"

#include "llama2_ctrl.h"

// The host-side reference is intentionally the same pinned upstream source as
// the guest. It catches arithmetic or compiler errors instead of blessing a
// fixed text generated by the BPF build itself.
#define main llama2_unused_native_main
#ifdef LLAMA2_QUANTIZED
#include "runq.c"
#else
#include "run.c"
#endif
#undef main

#ifdef LLAMA2_QUANTIZED
#include "llama2q.skel.h"
#define LLAMA_NAME "llama2-q8"
#define LLAMA_SKELETON struct llama2q
#define LLAMA_OPEN llama2q__open
#define LLAMA_DESTROY llama2q__destroy
#define LLAMA_CONTROL(skeleton) (&(skeleton)->data_qctrl->qctrl)
#define LLAMA_DRAIN(skeleton) ((skeleton)->progs.llama2q_drain)
#define LLAMA_RUN(skeleton) ((skeleton)->progs.llama2q_run)
#else
#include "llama2.skel.h"
#define LLAMA_NAME "llama2"
#define LLAMA_SKELETON struct llama2
#define LLAMA_OPEN llama2__open
#define LLAMA_DESTROY llama2__destroy
#define LLAMA_CONTROL(skeleton) (&(skeleton)->data_lctrl->lctrl)
#define LLAMA_DRAIN(skeleton) ((skeleton)->progs.llama2_drain)
#define LLAMA_RUN(skeleton) ((skeleton)->progs.llama2_run)
#endif

enum {
    LLAMA_OUTPUT_BYTES = 1u << 20,
    LLAMA_HEAP_BYTES = 8u << 20,
};

struct checkpoint_config {
    int32_t dim;
    int32_t hidden_dim;
    int32_t layers;
    int32_t heads;
    int32_t kv_heads;
    int32_t vocabulary;
    int32_t context;
};

_Static_assert(sizeof(struct checkpoint_config) == 7 * sizeof(int32_t), "llama2.c checkpoint header layout");

// run.c's parameters, with its defaults and validation.
struct options {
    const char* checkpoint;
    const char* tokenizer;
    float temperature;
    float topp;
    int steps;
    const char* prompt;
    unsigned long long seed;
};

// The kernel's own per-program counters, summed over the object: a wall clock
// around the syscall would also count the syscall path and this loop, which
// the native run does not pay. Run-time statistics must be enabled first.
static int kernel_run_time(struct bpf_object* object, uint64_t* nanoseconds, uint64_t* invocations) {
    uint64_t total_nanoseconds = 0;
    uint64_t total_invocations = 0;
    struct bpf_program* program;
    bpf_object__for_each_program(program, object) {
        int fd = bpf_program__fd(program);
        if (fd < 0) {
            continue;
        }
        struct bpf_prog_info info = {0};
        unsigned int length = sizeof(info);
        if (bpf_prog_get_info_by_fd(fd, &info, &length)) {
            return -1;
        }
        total_nanoseconds += info.run_time_ns;
        total_invocations += info.run_cnt;
    }
    *nanoseconds = total_nanoseconds;
    *invocations = total_invocations;
    return 0;
}

static void usage(void) {
    fprintf(stderr, "Usage:   %s <checkpoint> [options]\n", LLAMA_NAME);
    fprintf(stderr, "Example: %s model.bin -n 256 -i \"Once upon a time\"\n", LLAMA_NAME);
    fprintf(stderr, "Options:\n");
    fprintf(stderr, "  -t <float>  temperature in [0,inf], default 1.0\n");
    fprintf(stderr, "  -p <float>  p value in top-p (nucleus) sampling in [0,1] default 0.9\n");
    fprintf(stderr, "  -s <int>    random seed, default time(NULL)\n");
    fprintf(stderr, "  -n <int>    number of steps to run for, default 256. 0 = max_seq_len\n");
    fprintf(stderr, "  -i <string> input prompt\n");
    fprintf(stderr, "  -z <string> optional path to custom tokenizer\n");
}

static int parse_options(int argc, char** argv, struct options* options) {
    *options = (struct options){.tokenizer = "tokenizer.bin", .temperature = 1.0f, .topp = 0.9f, .steps = 256};
    if (argc < 2) {
        return -1;
    }
    options->checkpoint = argv[1];
    for (int i = 2; i < argc; i += 2) {
        if (i + 1 >= argc || argv[i][0] != '-' || strlen(argv[i]) != 2) {
            return -1;
        }
        switch (argv[i][1]) {
            case 't':
                options->temperature = (float)atof(argv[i + 1]);
                break;
            case 'p':
                options->topp = (float)atof(argv[i + 1]);
                break;
            case 's':
                options->seed = (unsigned long long)atoi(argv[i + 1]);
                break;
            case 'n':
                options->steps = atoi(argv[i + 1]);
                break;
            case 'i':
                options->prompt = argv[i + 1];
                break;
            case 'z':
                options->tokenizer = argv[i + 1];
                break;
            default:
                return -1;
        }
    }
    if (options->seed <= 0) {
        options->seed = (unsigned int)time(NULL);
    }
    if (options->temperature < 0.0f) {
        options->temperature = 0.0f;
    }
    if (options->topp < 0.0f || 1.0f < options->topp) {
        options->topp = 0.9f;
    }
    if (options->steps < 0) {
        options->steps = 0;
    }
    if (options->prompt && strlen(options->prompt) >= LLAMA2_PROMPT_MAX) {
        fprintf(stderr, "the prompt must be shorter than %u bytes\n", (unsigned int)LLAMA2_PROMPT_MAX);
        return -1;
    }
    return 0;
}

static int add_tensor_bytes(size_t* total, size_t a, size_t b, size_t c, size_t copies, size_t item_size) {
    const size_t factors[] = {a, b, c, copies, item_size};
    size_t bytes = 1;
    for (size_t i = 0; i < sizeof(factors) / sizeof(factors[0]); ++i) {
        if (factors[i] && bytes > SIZE_MAX / factors[i]) {
            return -1;
        }
        bytes *= factors[i];
    }
    if (*total > SIZE_MAX - bytes) {
        return -1;
    }
    *total += bytes;
    return 0;
}

#ifdef LLAMA2_QUANTIZED
static int add_quantized_tensor_bytes(size_t* total, size_t a, size_t b, size_t c, size_t copies, size_t group_size) {
    size_t before = *total;
    if (add_tensor_bytes(total, a, b, c, copies, 1)) {
        return -1;
    }
    size_t values = *total - before;
    if (values % group_size || add_tensor_bytes(total, values / group_size, 1, 1, 1, sizeof(float))) {
        return -1;
    }
    return 0;
}
#endif

// Reject a checkpoint the guest could not read safely before staging it.
static int validate_model(const unsigned char* model, size_t size) {
    struct checkpoint_config config;
    int shared_classifier;
#ifdef LLAMA2_QUANTIZED
    if (size < 256) {
        fprintf(stderr, "model is too short for a Q8-v2 header\n");
        return -1;
    }
    uint32_t magic = 0, version = 0;
    memcpy(&magic, model, sizeof(magic));
    memcpy(&version, model + sizeof(magic), sizeof(version));
    if (magic != 0x616b3432 || version != 2) {
        fprintf(stderr, "model is not a Q8-v2 checkpoint\n");
        return -1;
    }
    memcpy(&config, model + 8, sizeof(config));
    shared_classifier = model[8 + sizeof(config)];
    int32_t group_size = 0;
    memcpy(&group_size, model + 9 + sizeof(config), sizeof(group_size));
    if (shared_classifier > 1 || group_size <= 0 || config.dim % group_size || config.hidden_dim % group_size) {
        fprintf(stderr, "model has invalid Q8 parameters\n");
        return -1;
    }
#else
    if (size < sizeof(config)) {
        fprintf(stderr, "model is too short\n");
        return -1;
    }
    memcpy(&config, model, sizeof(config));
    if (config.vocabulary == INT32_MIN) {
        fprintf(stderr, "model has an invalid vocabulary size\n");
        return -1;
    }
    shared_classifier = config.vocabulary > 0;
    if (!shared_classifier) {
        config.vocabulary = -config.vocabulary;
    }
#endif
    if (config.dim <= 0 || (config.dim & 1) || config.hidden_dim <= 0 || config.layers <= 0 || config.heads <= 0 || config.kv_heads <= 0 ||
        config.heads % config.kv_heads || config.dim % config.heads || ((config.dim / config.heads) & 1) || config.vocabulary <= 1 || config.context <= 0) {
        fprintf(stderr, "model has an invalid configuration\n");
        return -1;
    }
    size_t dim = (size_t)config.dim;
    size_t hidden = (size_t)config.hidden_dim;
    size_t layers = (size_t)config.layers;
    size_t vocabulary = (size_t)config.vocabulary;
    size_t head_size = dim / (size_t)config.heads;
    size_t kv_dim = head_size * (size_t)config.kv_heads;
#ifdef LLAMA2_QUANTIZED
    size_t required = 256;
    size_t group = (size_t)group_size;
    int invalid_size = add_tensor_bytes(&required, layers, dim, 1, 2, sizeof(float)) || add_tensor_bytes(&required, dim, 1, 1, 1, sizeof(float)) ||
        add_quantized_tensor_bytes(&required, vocabulary, dim, 1, 1, group) || add_quantized_tensor_bytes(&required, layers, dim, dim, 2, group) ||
        add_quantized_tensor_bytes(&required, layers, dim, kv_dim, 2, group) || add_quantized_tensor_bytes(&required, layers, dim, hidden, 3, group) ||
        (!shared_classifier && add_quantized_tensor_bytes(&required, vocabulary, dim, 1, 1, group));
#else
    size_t required = sizeof(config);
    size_t context = (size_t)config.context;
    int invalid_size = add_tensor_bytes(&required, vocabulary, dim, 1, 1, sizeof(float)) || add_tensor_bytes(&required, layers, dim, 1, 2, sizeof(float)) ||
        add_tensor_bytes(&required, layers, dim, dim, 2, sizeof(float)) || add_tensor_bytes(&required, layers, dim, kv_dim, 2, sizeof(float)) ||
        add_tensor_bytes(&required, layers, dim, hidden, 3, sizeof(float)) || add_tensor_bytes(&required, dim, 1, 1, 1, sizeof(float)) ||
        add_tensor_bytes(&required, context, head_size / 2, 1, 2, sizeof(float)) ||
        (!shared_classifier && add_tensor_bytes(&required, vocabulary, dim, 1, 1, sizeof(float)));
#endif
    if (invalid_size || size < required) {
        fprintf(stderr, "model is truncated or its dimensions overflow the checkpoint layout\n");
        return -1;
    }
    return 0;
}

static unsigned char* read_file(const char* path, size_t* size) {
    FILE* file = fopen(path, "rb");
    if (!file) {
        perror(path);
        return NULL;
    }
    unsigned char* data = NULL;
    long end = fseek(file, 0, SEEK_END) ? -1 : ftell(file);
    if (end <= 0) {
        fprintf(stderr, "cannot determine the size of %s\n", path);
    } else if ((data = malloc((size_t)end)) == NULL || fseek(file, 0, SEEK_SET) || fread(data, 1, (size_t)end, file) != (size_t)end) {
        fprintf(stderr, "cannot read %s\n", path);
        free(data);
        data = NULL;
    } else {
        *size = (size_t)end;
    }
    fclose(file);
    return data;
}

// The number of continuations a run may use; unlimited unless the environment
// caps it, so a regression in the drive budget can be turned into a failure.
static int read_max_drains(unsigned long* result) {
    const char* text = getenv("BPF_CAPSULE_MAX_DRAINS");
    *result = ULONG_MAX;
    if (!text || !*text) {
        return 0;
    }
    char* end = NULL;
    errno = 0;
    unsigned long value = strtoul(text, &end, 10);
    if (text[0] < '0' || text[0] > '9' || errno || !end || *end) {
        fprintf(stderr, "BPF_CAPSULE_MAX_DRAINS must be a non-negative integer\n");
        return -1;
    }
    *result = value;
    return 0;
}

static double milliseconds_since(const struct timespec* start, clockid_t clock) {
    struct timespec now;
    clock_gettime(clock, &now);
    return (double)(now.tv_sec - start->tv_sec) * 1e3 + (double)(now.tv_nsec - start->tv_nsec) / 1e6;
}

// The same generation natively, with generate()'s stdout captured into a
// buffer and its tokens-per-second line dropped. *milliseconds receives the
// CPU time of the generation, excluding the checkpoint and tokenizer loads.
static char* generate_native(const struct options* options, size_t* length, double* milliseconds) {
    Transformer transformer;
    build_transformer(&transformer, (char*)options->checkpoint);
    int steps = options->steps;
    if (steps == 0 || steps > transformer.config.seq_len) {
        steps = transformer.config.seq_len;
    }
    Tokenizer tokenizer;
    build_tokenizer(&tokenizer, (char*)options->tokenizer, transformer.config.vocab_size);
    Sampler sampler;
    build_sampler(&sampler, transformer.config.vocab_size, options->temperature, options->topp, options->seed);

    char* text = NULL;
    FILE* capture = tmpfile();
    int saved_stdout = dup(STDOUT_FILENO);
    int saved_stderr = dup(STDERR_FILENO);
    int null = open("/dev/null", O_WRONLY);
    if (!capture || saved_stdout < 0 || saved_stderr < 0 || null < 0) {
        perror("capture native output");
        goto cleanup;
    }
    fflush(stdout);
    fflush(stderr);
    dup2(fileno(capture), STDOUT_FILENO);
    dup2(null, STDERR_FILENO);
    struct timespec start;
    clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &start);
    generate(&transformer, &tokenizer, &sampler, (char*)options->prompt, steps);
    *milliseconds = milliseconds_since(&start, CLOCK_PROCESS_CPUTIME_ID);
    fflush(stdout);
    dup2(saved_stdout, STDOUT_FILENO);
    dup2(saved_stderr, STDERR_FILENO);

    long end = fseek(capture, 0, SEEK_END) ? -1 : ftell(capture);
    if (end < 0) {
        perror("capture native output");
        goto cleanup;
    }
    text = malloc((size_t)end + 1);
    if (!text || fseek(capture, 0, SEEK_SET) || fread(text, 1, (size_t)end, capture) != (size_t)end) {
        perror("capture native output");
        free(text);
        text = NULL;
        goto cleanup;
    }
    text[end] = 0;
    *length = (size_t)end;

cleanup:
    if (capture) {
        fclose(capture);
    }
    if (saved_stdout >= 0) {
        close(saved_stdout);
    }
    if (saved_stderr >= 0) {
        close(saved_stderr);
    }
    if (null >= 0) {
        close(null);
    }
    free_sampler(&sampler);
    free_tokenizer(&tokenizer);
    free_transformer(&transformer);
    return text;
}

int main(int argc, char** argv) {
    struct options options;
    if (parse_options(argc, argv, &options)) {
        usage();
        return 1;
    }
    unsigned long max_drains = 0;
    if (read_max_drains(&max_drains)) {
        return 1;
    }

    int result = 1;
    int stats_fd = -1;
    unsigned char* model = NULL;
    unsigned char* tokenizer = NULL;
    char* native_text = NULL;
    LLAMA_SKELETON* skeleton = NULL;
    struct bpf_capsule capsule = {0};

    size_t model_size = 0;
    size_t tokenizer_size = 0;
    model = read_file(options.checkpoint, &model_size);
    tokenizer = model ? read_file(options.tokenizer, &tokenizer_size) : NULL;
    if (!model || !tokenizer || validate_model(model, model_size)) {
        goto cleanup;
    }

    skeleton = LLAMA_OPEN();
    if (!skeleton) {
        fprintf(stderr, "open failed\n");
        goto cleanup;
    }
    if (bpf_capsule_configure(&capsule, skeleton->obj,
            (struct bpf_capsule_config){
                .fiber_count = 1,
                .heap_bytes = model_size + tokenizer_size + LLAMA_OUTPUT_BYTES + LLAMA_HEAP_BYTES,
            }) ||
        bpf_object__load_skeleton(skeleton->skeleton) || bpf_capsule_initialize(&capsule)) {
        fprintf(stderr, "load failed: %s\n", strerror(errno));
        goto cleanup;
    }

    volatile struct llama2_bpf_ctrl* control = LLAMA_CONTROL(skeleton);
    unsigned char* model_address = bpf_capsule_malloc(&capsule, model_size);
    unsigned char* tokenizer_address = bpf_capsule_malloc(&capsule, tokenizer_size);
    char* output_address = bpf_capsule_malloc(&capsule, LLAMA_OUTPUT_BYTES);
    if (!model_address || !tokenizer_address || !output_address) {
        perror("allocate Capsule memory");
        goto cleanup;
    }
    memcpy(model_address, model, model_size);
    memcpy(tokenizer_address, tokenizer, tokenizer_size);
    control->model = model_address;
    control->model_size = model_size;
    control->tokenizer = tokenizer_address;
    control->tokenizer_size = tokenizer_size;
    control->output = output_address;
    control->output_capacity = LLAMA_OUTPUT_BYTES;
    control->output_size = 0;
    control->temperature = options.temperature;
    control->topp = options.topp;
    control->seed = options.seed;
    control->steps = options.steps;
    control->has_prompt = options.prompt != NULL;
    if (options.prompt) {
        strcpy((char*)control->prompt, options.prompt);
    }

    int drain_fd = bpf_program__fd(LLAMA_DRAIN(skeleton));
    int run_fd = bpf_program__fd(LLAMA_RUN(skeleton));
    if (drain_fd < 0 || run_fd < 0) {
        fprintf(stderr, "BPF object is missing a %s program\n", LLAMA_NAME);
        goto cleanup;
    }
    stats_fd = bpf_enable_stats(BPF_STATS_RUN_TIME);
    uint64_t kernel_before = 0, invocations_before = 0;
    int stats_failed = stats_fd < 0 || kernel_run_time(skeleton->obj, &kernel_before, &invocations_before);
    struct bpf_test_run_opts test_run = {.sz = sizeof(test_run)};
    if (bpf_prog_test_run_opts(run_fd, &test_run)) {
        perror("run");
        goto cleanup;
    }
    unsigned long drains = 0;
    while (control->capsule.status == CAPSULE_PENDING) {
        if (drains == max_drains) {
            fprintf(stderr, "computation is still pending after %lu drains; set BPF_CAPSULE_MAX_DRAINS to permit more\n", drains);
            goto cleanup;
        }
        if (bpf_prog_test_run_opts(drain_fd, &test_run)) {
            perror("drain");
            goto cleanup;
        }
        drains++;
    }
    uint64_t kernel_after = 0, invocations_after = 0;
    stats_failed = stats_failed || kernel_run_time(skeleton->obj, &kernel_after, &invocations_after);
    if (control->capsule.status != CAPSULE_OK) {
        if (control->capsule.status == CAPSULE_EXITED && control->capsule.code < 0) {
            fprintf(stderr, "capsule stopped: %s (%lld)\n", bpf_capsule_error_string(control->capsule.code), (long long)control->capsule.code);
        } else if (control->capsule.status == CAPSULE_EXITED) {
            fprintf(stderr, "capsule exited with code %lld\n", (long long)control->capsule.code);
        } else {
            fprintf(stderr, "capsule status=%s\n", bpf_capsule_status_string(control->capsule.status));
        }
        goto cleanup;
    }
    if (control->output_size > control->output_capacity) {
        fprintf(stderr, "the generated text requires %zu bytes; the buffer holds %zu\n", control->output_size, control->output_capacity);
        goto cleanup;
    }
    size_t kernel_length = control->output_size;
    fwrite(output_address, 1, kernel_length, stdout);
    fflush(stdout);

    size_t native_length = 0;
    double native_ms = 0;
    native_text = generate_native(&options, &native_length, &native_ms);
    if (!native_text) {
        goto cleanup;
    }
    if (native_length != kernel_length || memcmp(native_text, output_address, kernel_length)) {
        fprintf(stderr, "in-kernel text differs from native llama2.c:\n%s", native_text);
        goto cleanup;
    }
    fprintf(stderr, "native reference: match\n");
    if (!stats_failed) {
        fprintf(stderr, "kernel execution: %.3f ms over %llu invocations\n", (double)(kernel_after - kernel_before) / 1e6,
            (unsigned long long)(invocations_after - invocations_before));
    }
    fprintf(stderr, "native execution: %.3f ms\n", native_ms);
    fprintf(stderr, "continuation drains: %lu\n", drains);
    result = 0;

cleanup:
    if (stats_fd >= 0) {
        close(stats_fd);
    }
    if (skeleton) {
        (void)bpf_capsule_release(&capsule);
        LLAMA_DESTROY(skeleton);
    }
    free(native_text);
    free(tokenizer);
    free(model);
    return result;
}
