CREATE TABLE t(a INTEGER PRIMARY KEY, b INTEGER, c TEXT);
WITH RECURSIVE r(i) AS (VALUES(1) UNION ALL SELECT i + 1 FROM r WHERE i < 500)
INSERT INTO t SELECT i, i * i, 'row-' || i FROM r;
SELECT count(*), sum(b) FROM t;
SELECT c FROM t WHERE a % 97 = 0 ORDER BY a DESC;
SELECT b FROM t WHERE c LIKE 'row-1%' ORDER BY a LIMIT 5;
SELECT 12.5 / 2.0;
