// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#pragma once

// Compiler-only indices into the records defined by the private object ABI.
// LLVM struct types retain field order but not C field names.
enum __bpf_capsule_fiber_control_field {
    BPF_CAPSULE_FIBER_CONTROL_STATUS,
    BPF_CAPSULE_FIBER_CONTROL_CODE,
    BPF_CAPSULE_FIBER_CONTROL_GENERATION,
    BPF_CAPSULE_FIBER_CONTROL_SP,
    BPF_CAPSULE_FIBER_CONTROL_FP,
    BPF_CAPSULE_FIBER_CONTROL_PC,
    BPF_CAPSULE_FIBER_CONTROL_RETURN_SIZE,
    BPF_CAPSULE_FIBER_CONTROL_FIELD_COUNT,
};

enum __bpf_capsule_object_config_field {
    BPF_CAPSULE_OBJECT_CONFIG_HEAP_BASE,
    BPF_CAPSULE_OBJECT_CONFIG_HEAP_BYTES,
    BPF_CAPSULE_OBJECT_CONFIG_STACK_BASE,
    BPF_CAPSULE_OBJECT_CONFIG_MEMORY_END,
    BPF_CAPSULE_OBJECT_CONFIG_FIBER_COUNT,
    BPF_CAPSULE_OBJECT_CONFIG_STACK_BYTES_PER_FIBER,
    BPF_CAPSULE_OBJECT_CONFIG_MAX_FIBERS,
    BPF_CAPSULE_OBJECT_CONFIG_ARENA_IMAGE_PAGES,
    BPF_CAPSULE_OBJECT_CONFIG_MEMORY_BACKEND,
    BPF_CAPSULE_OBJECT_CONFIG_HEAP_RESERVED,
    BPF_CAPSULE_OBJECT_CONFIG_ABI_MAGIC,
    BPF_CAPSULE_OBJECT_CONFIG_ABI_VERSION,
    BPF_CAPSULE_OBJECT_CONFIG_MEMORY_VIEW_BASE,
    BPF_CAPSULE_OBJECT_CONFIG_FIELD_COUNT,
};
